name: Lint
on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    steps:
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1.3.2
        with:
          terraform_version: 1.0.1

      - name: Checkout code
        uses: actions/checkout@v2.3.4

      - name: Run terraform init
        run: terraform init -backend=false

      - name: Run terraform validate
        run: terraform validate

      - name: Run terraform fmt
        run: terraform fmt -recursive -check

  # See https://github.com/hashicorp/terraform/issues/28041
  terraform-providers:
    name: Terraform Providers
    runs-on: ubuntu-latest
    steps:
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1.3.2
        with:
          terraform_version: 1.0.1

      - name: Checkout code
        uses: actions/checkout@v2.3.4

      - name: Run terraform init
        run: terraform init -backend=false

      - name: Run terraform providers lock
        run: |
          terraform providers lock \
            -platform=darwin_amd64 \
            -platform=darwin_arm64 \
            -platform=freebsd_386 \
            -platform=freebsd_amd64 \
            -platform=freebsd_arm \
            -platform=freebsd_arm64 \
            -platform=linux_386 \
            -platform=linux_amd64 \
            -platform=linux_arm \
            -platform=linux_arm64 \
            -platform=windows_386 \
            -platform=windows_amd64 \
            -platform=windows_arm

      - name: Run git diff
        run: git diff --exit-code
