name: Terraform Plan
on:
  pull_request_target:

jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    steps:
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1.3.2
        with:
          terraform_version: 1.0.1
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Checkout code
        uses: actions/checkout@v2.3.4

      - name: Run terraform init
        run: terraform init

      - name: Run terraform plan
        id: plan
        run: terraform plan
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

      - name: Create comment
        uses: actions/github-script@4.0.2
        env:
          plan_stdout: ${{ steps.plan.outputs.stdout }}
          plan_outcome: ${{ steps.plan.outcome }}
        with:
          script: |
            // https://stackoverflow.com/a/30970751/4747401
            function escapeHTML(s) {
                const lookup = {
                    '&': "&amp;",
                    '"': "&quot;",
                    '<': "&lt;",
                    '>': "&gt;',
                }
                return s.replace(/[&"<>]/g, (c) => lookup[c])
            }

            const outcome = escapeHTML(process.env.plan_outcome)
            const output = escapeHTML(process.env.plan_stdout)

            const output = `### Terraform
            <details>
            <summary>terraform plan: ${outcome}</summary>
            <pre>${output}</pre>
            </details>`

            await github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output,
            })
